In [8]:
import pandas as pd
from pathlib import Path

In [12]:
params_data_path = Path.cwd() / "log_params_bayesian.parquet"
data_params = pd.read_parquet(params_data_path)

In [14]:
data_params.describe()

,trial_id,value,n_pivots,n_clusters,n_lookback,hold_period
count,2490.000000,2490.000000,2490.000000,2490.000000,2490.000000,2490.000000
mean,1252.164257,14.003550,3.581928,14.482329,18.350201,3.562249
std,720.172332,9.954636,0.839892,2.816165,16.742257,3.360779
min,0.000000,0.078610,3.000000,3.000000,8.000000,1.000000
25%,629.250000,6.570290,3.000000,15.000000,11.000000,2.000000
50%,1252.500000,11.401042,3.000000,16.000000,14.000000,3.000000
75%,1874.750000,19.289198,4.000000,16.000000,18.000000,4.000000
max,2499.000000,52.813872,8.000000,16.000000,120.000000,24.000000